os: "linux"

language: python

dist: "xenial"
python: "3.7"

install:
  - pip install pipenv
  - pipenv install --dev

script: pipenv run pelican -s publishconf.py

deploy:
  provider: pages
  strategy: git
  repo: "vazqueztomas/vazqueztomas.github.io"
  target_branch: online
  local_dir: output
  github_token: $GITHUB_TOKEN
  edge: true
  on:
    branch: master